### ISSUE TITLE
Reference for docker image in airflow.yaml?

### ISSUE THREAD

**Issue by donjae** [bloomberg/airflow#53]
Hi, 

I was wondering there was a specific image that was being referenced in the `airflow.yaml` deployment, since there is no official airflow image available. 

**see following:**

```
 spec:
      initContainers:
      - name: "init"
        image: airflow
        imagePullPolicy: IfNotPresent
```
